/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alpha;

/**
 *
 * @author Caleb
 */
public class distAddRem extends javax.swing.JFrame {
    private GUI mainframe;

    /**
     * Creates new form semesterAddRem
     * and gets a reference to the window that created this pop-up
     */
    public distAddRem(GUI mainframe) {
        initComponents();
        this.mainframe = mainframe;
    }
    
    private void addDistNameTextReset(){
        addDistNameText.setForeground(new java.awt.Color(153, 153, 153));
        addDistNameText.setText("ex. Exam");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAddDist = new javax.swing.JPanel();
        addDistCBoxSemester = new javax.swing.JComboBox<>();
        addButCancel = new javax.swing.JButton();
        addButCreateDist = new javax.swing.JButton();
        addDistNameText = new javax.swing.JTextField();
        addDistNameTitle = new javax.swing.JLabel();
        addDistWeightTitle = new javax.swing.JLabel();
        addDistSpinnerWeight = new javax.swing.JSpinner();
        addDistCBoxClass = new javax.swing.JComboBox<>();
        panelRemDist = new javax.swing.JPanel();
        remScrollPane = new javax.swing.JScrollPane();
        remList = new javax.swing.JList<>();
        remButCancel = new javax.swing.JButton();
        remButRemDist = new javax.swing.JButton();
        remDistCBoxSemester = new javax.swing.JComboBox<>();
        remDistCBoxClass = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("Add/Remove Distribution");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                distAddRem.this.windowClosing(evt);
            }
        });

        addDistCBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester...", "Item 2", "Item 3", "Item 4" }));
        addDistCBoxSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDistCBoxSemesterActionPerformed1(evt);
            }
        });

        addButCancel.setText("Cancel");
        addButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButCancelActionPerformed(evt);
            }
        });

        addButCreateDist.setText("Create Distribution");
        addButCreateDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButCreateDistActionPerformed(evt);
            }
        });

        addDistNameText.setForeground(new java.awt.Color(153, 153, 153));
        addDistNameText.setText("ex. Exam");
        addDistNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addDistNameTextFocusLost(evt);
            }
        });
        addDistNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDistNameTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addDistNameTextMouseEntered(evt);
            }
        });

        addDistNameTitle.setText("Distribution Name");

        addDistWeightTitle.setText("Distribution Weight");

        addDistSpinnerWeight.setModel(new javax.swing.SpinnerNumberModel(25.0d, 0.0d, 100.0d, 0.5d));
        addDistSpinnerWeight.setEditor(new javax.swing.JSpinner.NumberEditor(addDistSpinnerWeight, ".#"));

        addDistCBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class...", "Item 2", "Item 3", "Item 4" }));
        addDistCBoxClass.setToolTipText("Select your class here");

        javax.swing.GroupLayout panelAddDistLayout = new javax.swing.GroupLayout(panelAddDist);
        panelAddDist.setLayout(panelAddDistLayout);
        panelAddDistLayout.setHorizontalGroup(
            panelAddDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddDistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addDistCBoxClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddDistLayout.createSequentialGroup()
                        .addGroup(panelAddDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addDistNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addDistWeightTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAddDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButCreateDist, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(addDistNameText)
                            .addComponent(addDistSpinnerWeight)))
                    .addComponent(addDistCBoxSemester, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAddDistLayout.setVerticalGroup(
            panelAddDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddDistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDistCBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDistCBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAddDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addDistNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDistNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDistWeightTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDistSpinnerWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButCancel)
                    .addComponent(addButCreateDist))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Distribution", panelAddDist);

        remList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        remScrollPane.setViewportView(remList);

        remButCancel.setText("Cancel");
        remButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remButCancelActionPerformed(evt);
            }
        });

        remButRemDist.setText("Remove Distribution");
        remButRemDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remButRemDistActionPerformed(evt);
            }
        });

        remDistCBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester...", "Item 2", "Item 3", "Item 4" }));
        remDistCBoxSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remDistCBoxSemesterActionPerformed1(evt);
            }
        });

        remDistCBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class...", "Item 2", "Item 3", "Item 4" }));
        remDistCBoxClass.setToolTipText("Select your class here");

        javax.swing.GroupLayout panelRemDistLayout = new javax.swing.GroupLayout(panelRemDist);
        panelRemDist.setLayout(panelRemDistLayout);
        panelRemDistLayout.setHorizontalGroup(
            panelRemDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRemDistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(remDistCBoxClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRemDistLayout.createSequentialGroup()
                        .addComponent(remButCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remButRemDist, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addComponent(remDistCBoxSemester, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRemDistLayout.setVerticalGroup(
            panelRemDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemDistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remDistCBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remDistCBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRemDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remButCancel)
                    .addComponent(remButRemDist))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove Distribution", panelRemDist);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("panelAddRemClass");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Action taken when file->exit is taken. Simply closes the entire system (The entire app)
    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fileExitActionPerformed

    // Action performed when the cancel button on the add Semester tab is clicked
    // Currently re-enables the original GUI
    // Then disposes the pop-up window
    private void addButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButCancelActionPerformed
        // TODO add your handling code here:
        mainframe.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_addButCancelActionPerformed

    // Action performed when window is closed
    // Currently re-enables the original GUI that instantiated this pop-up window
    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
        // TODO add your handling code here:
        mainframe.setEnabled(true);
    }//GEN-LAST:event_windowClosing

    //Action performed when cancel button on remove tab
    // Currently re-enables the original GUI that instantiated this pop-up window
    // Then disposes the pop-up window
    private void remButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remButCancelActionPerformed
        // TODO add your handling code here:
        mainframe.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_remButCancelActionPerformed

    private void addDistCBoxSemesterActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDistCBoxSemesterActionPerformed1
        addDistCBoxSemester.setModel(new javax.swing.DefaultComboBoxModel(mainframe.listClasses((String) addDistCBoxSemester.getSelectedItem())));
    }//GEN-LAST:event_addDistCBoxSemesterActionPerformed1

    private void remDistCBoxSemesterActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remDistCBoxSemesterActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_remDistCBoxSemesterActionPerformed1

    private void addDistNameTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDistNameTextMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addDistNameTextMouseEntered

    private void addDistNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addDistNameTextFocusLost
        // TODO add your handling code here:
        if(addDistNameText.getText().equals(""))addDistNameTextReset();
    }//GEN-LAST:event_addDistNameTextFocusLost

    private void addDistNameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDistNameTextMouseClicked
        // TODO add your handling code here:
        if(addDistNameText.getText().equals("ex. Exam")){
            addDistNameText.setText("");
            addDistNameText.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_addDistNameTextMouseClicked

    private void addButCreateDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButCreateDistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButCreateDistActionPerformed

    private void remButRemDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remButRemDistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remButRemDistActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButCancel;
    private javax.swing.JButton addButCreateDist;
    private javax.swing.JComboBox<String> addDistCBoxClass;
    private javax.swing.JComboBox<String> addDistCBoxSemester;
    private javax.swing.JTextField addDistNameText;
    private javax.swing.JLabel addDistNameTitle;
    private javax.swing.JSpinner addDistSpinnerWeight;
    private javax.swing.JLabel addDistWeightTitle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelAddDist;
    private javax.swing.JPanel panelRemDist;
    private javax.swing.JButton remButCancel;
    private javax.swing.JButton remButRemDist;
    private javax.swing.JComboBox<String> remDistCBoxClass;
    private javax.swing.JComboBox<String> remDistCBoxSemester;
    private javax.swing.JList<String> remList;
    private javax.swing.JScrollPane remScrollPane;
    // End of variables declaration//GEN-END:variables
}
