/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alpha;

import java.util.ArrayList;

/**
 *
 * @author Caleb
 */
public class GUI extends javax.swing.JFrame {
    private ArrayList<classHandler> semesters;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        this.semesters = new ArrayList<classHandler>();
        initComponents();
    }
    
    public void addSemester(classHandler semester){
        semesters.add(semester);
    }
    
    public void removeSemester(int index){
        semesters.remove(index);
    }
    
    public void editSemester(int index, classHandler semester){
        semesters.set(index, semester);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winTabs = new javax.swing.JTabbedPane();
        panHome = new javax.swing.JPanel();
        homeTitle = new java.awt.Label();
        homeInfoScroll = new javax.swing.JScrollPane();
        homeInfo = new javax.swing.JTextPane();
        panOverview = new javax.swing.JPanel();
        overviewCBoxSemester = new javax.swing.JComboBox<>();
        overviewCBoxClass = new javax.swing.JComboBox<>();
        overviewCBoxDistribution = new javax.swing.JComboBox<>();
        overviewGradeNameScroll = new javax.swing.JScrollPane();
        overviewGradeNameInfo = new javax.swing.JList<>();
        overviewAverageScroll = new javax.swing.JScrollPane();
        overviewAverageInfo = new javax.swing.JTextPane();
        overviewGradeScroll = new javax.swing.JScrollPane();
        overviewGradeInfo = new javax.swing.JList<>();
        overviewDistScroll = new javax.swing.JScrollPane();
        overviewDistInfo = new javax.swing.JList<>();
        overviewGradeNameTitle = new java.awt.Label();
        overviewGradeTitle = new java.awt.Label();
        overviewDistTitle = new java.awt.Label();
        panEdit = new javax.swing.JPanel();
        editClassesTitle = new java.awt.Label();
        editCBoxSemester = new javax.swing.JComboBox<>();
        editButAddRemSemester = new javax.swing.JButton();
        editCBoxClass = new javax.swing.JComboBox<>();
        editClassDistSeperator = new javax.swing.JSeparator();
        editButAddRemClass = new javax.swing.JButton();
        editButEditSemester = new javax.swing.JButton();
        editButEditClass = new javax.swing.JButton();
        editCBoxDistSemester = new javax.swing.JComboBox<>();
        editClassesSeperator = new javax.swing.Box.Filler(new java.awt.Dimension(0, 24), new java.awt.Dimension(0, 24), new java.awt.Dimension(32767, 24));
        editDistScroll = new javax.swing.JScrollPane();
        editDistInfo = new javax.swing.JList<>();
        editDistTitle = new java.awt.Label();
        editDistCBoxSeperator = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        editCBoxDistClass = new javax.swing.JComboBox<>();
        editButAddRemDist = new javax.swing.JButton();
        editDistSeperator = new javax.swing.Box.Filler(new java.awt.Dimension(0, 31), new java.awt.Dimension(0, 31), new java.awt.Dimension(32767, 31));
        editButEditDist = new javax.swing.JButton();
        panPredict = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        fileExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YOCA - Your Own Class Assistant");
        setPreferredSize(new java.awt.Dimension(510, 515));
        setResizable(false);

        panHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        homeTitle.setAlignment(java.awt.Label.CENTER);
        homeTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        homeTitle.setText("YOCA");

        homeInfo.setText("Welcome to YOCA, Your Own Class Assistant!\n\nYOCA is an application that is here to help you keep track of and even predict grades necessary to your success! Here are a few instructions to get you started.\n\nClass Overview - Here, you can see all of your grades and see their impact on your overall average in the class\n\nEdit Classes - This tab allows you to create a new class, as well as enter in new grades or remove others. You also add your classes distributions here, so you can keep track of grades a little better!\n\nPredict! -  This tab allows you to estimate what grade you'll need on that final exam or big project for an A! You are able to input which distribution it will apply to, your desired end grade, and 'Predict!' will tell you what your goal grade is! ");
        homeInfoScroll.setViewportView(homeInfo);

        javax.swing.GroupLayout panHomeLayout = new javax.swing.GroupLayout(panHome);
        panHome.setLayout(panHomeLayout);
        panHomeLayout.setHorizontalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
            .addComponent(homeInfoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panHomeLayout.setVerticalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHomeLayout.createSequentialGroup()
                .addComponent(homeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeInfoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        winTabs.addTab("Home", panHome);

        panOverview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        overviewCBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester...", "Item 2", "Item 3", "Item 4" }));

        overviewCBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class...", "Item 2", "Item 3", "Item 4" }));

        overviewCBoxDistribution.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Distribution...", "Overall", "Item 3", "Item 4" }));
        overviewCBoxDistribution.setToolTipText("Select your class here");
        overviewCBoxDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewCBoxDistributionActionPerformed(evt);
            }
        });

        overviewGradeNameInfo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        overviewGradeNameScroll.setViewportView(overviewGradeNameInfo);

        overviewAverageInfo.setText("Total Average Here");
        overviewAverageScroll.setViewportView(overviewAverageInfo);
        overviewAverageInfo.getAccessibleContext().setAccessibleName("");

        overviewGradeInfo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        overviewGradeScroll.setViewportView(overviewGradeInfo);

        overviewDistInfo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        overviewDistScroll.setViewportView(overviewDistInfo);

        overviewGradeNameTitle.setText("Grade Name");

        overviewGradeTitle.setText("Grade");

        overviewDistTitle.setText("Distribution");

        javax.swing.GroupLayout panOverviewLayout = new javax.swing.GroupLayout(panOverview);
        panOverview.setLayout(panOverviewLayout);
        panOverviewLayout.setHorizontalGroup(
            panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewCBoxSemester, javax.swing.GroupLayout.Alignment.TRAILING, 0, 224, Short.MAX_VALUE)
                    .addComponent(overviewGradeNameTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overviewGradeNameScroll, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(overviewAverageScroll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOverviewLayout.createSequentialGroup()
                        .addGroup(panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(overviewGradeTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(overviewGradeScroll, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(overviewDistScroll)
                            .addComponent(overviewDistTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(overviewCBoxClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overviewCBoxDistribution, 0, 241, Short.MAX_VALUE))
                .addContainerGap())
        );
        panOverviewLayout.setVerticalGroup(
            panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(overviewCBoxSemester, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(overviewCBoxClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(overviewAverageScroll)
                    .addComponent(overviewCBoxDistribution, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewGradeNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overviewGradeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overviewDistTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewGradeScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(overviewGradeNameScroll)
                    .addComponent(overviewDistScroll))
                .addGap(71, 71, 71))
        );

        winTabs.addTab("Class Overview", panOverview);

        panEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        editClassesTitle.setAlignment(java.awt.Label.CENTER);
        editClassesTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        editClassesTitle.setText("Edit Classes");

        editCBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester...", "Item 2", "Item 3", "Item 4" }));
        editCBoxSemester.setToolTipText("Select your class here");
        editCBoxSemester.setPreferredSize(new java.awt.Dimension(91, 20));

        editButAddRemSemester.setText("Add/Remove Semester");

        editCBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class...", "Item 2", "Item 3", "Item 4" }));

        editButAddRemClass.setText("Add/Remove Class");

        editButEditSemester.setText("Edit Semester");

        editButEditClass.setText("Edit Class");
        editButEditClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButEditClassActionPerformed(evt);
            }
        });

        editCBoxDistSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester...", "Item 2", "Item 3", "Item 4" }));

        editDistInfo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        editDistScroll.setViewportView(editDistInfo);

        editDistTitle.setAlignment(java.awt.Label.CENTER);
        editDistTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        editDistTitle.setText("Edit Distributions");

        editCBoxDistClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class...", "Item 2", "Item 3", "Item 4" }));

        editButAddRemDist.setText("Add/Remove Distribution");

        editButEditDist.setText("Edit Distribution");

        javax.swing.GroupLayout panEditLayout = new javax.swing.GroupLayout(panEdit);
        panEdit.setLayout(panEditLayout);
        panEditLayout.setHorizontalGroup(
            panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editClassesTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editDistScroll)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEditLayout.createSequentialGroup()
                        .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editCBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButAddRemSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButEditSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editClassesSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editButAddRemClass, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEditLayout.createSequentialGroup()
                        .addComponent(editCBoxDistSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editDistCBoxSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCBoxDistClass, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editClassDistSeperator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editDistTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panEditLayout.createSequentialGroup()
                        .addComponent(editButAddRemDist, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editDistSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButEditDist, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panEditLayout.setVerticalGroup(
            panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editClassesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panEditLayout.createSequentialGroup()
                        .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editCBoxClass)
                            .addComponent(editCBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editButAddRemSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButAddRemClass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editButEditClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButEditSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(editClassesSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editClassDistSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(editDistTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editCBoxDistSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDistCBoxSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editCBoxDistClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editDistScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(editButAddRemDist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editDistSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButEditDist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        winTabs.addTab("Edit Classes", panEdit);

        panPredict.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panPredictLayout = new javax.swing.GroupLayout(panPredict);
        panPredict.setLayout(panPredictLayout);
        panPredictLayout.setHorizontalGroup(
            panPredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        panPredictLayout.setVerticalGroup(
            panPredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        winTabs.addTab("Predict!", panPredict);

        mnuFile.setText("File");

        fileExit.setText("Exit");
        fileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        mnuFile.add(fileExit);

        jMenuBar1.add(mnuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winTabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fileExitActionPerformed

    private void overviewCBoxDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewCBoxDistributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overviewCBoxDistributionActionPerformed

    private void editButEditClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButEditClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButEditClassActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButAddRemClass;
    private javax.swing.JButton editButAddRemDist;
    private javax.swing.JButton editButAddRemSemester;
    private javax.swing.JButton editButEditClass;
    private javax.swing.JButton editButEditDist;
    private javax.swing.JButton editButEditSemester;
    private javax.swing.JComboBox<String> editCBoxClass;
    private javax.swing.JComboBox<String> editCBoxDistClass;
    private javax.swing.JComboBox<String> editCBoxDistSemester;
    private javax.swing.JComboBox<String> editCBoxSemester;
    private javax.swing.JSeparator editClassDistSeperator;
    private javax.swing.Box.Filler editClassesSeperator;
    private java.awt.Label editClassesTitle;
    private javax.swing.Box.Filler editDistCBoxSeperator;
    private javax.swing.JList<String> editDistInfo;
    private javax.swing.JScrollPane editDistScroll;
    private javax.swing.Box.Filler editDistSeperator;
    private java.awt.Label editDistTitle;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JTextPane homeInfo;
    private javax.swing.JScrollPane homeInfoScroll;
    private java.awt.Label homeTitle;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JTextPane overviewAverageInfo;
    private javax.swing.JScrollPane overviewAverageScroll;
    private javax.swing.JComboBox<String> overviewCBoxClass;
    private javax.swing.JComboBox<String> overviewCBoxDistribution;
    private javax.swing.JComboBox<String> overviewCBoxSemester;
    private javax.swing.JList<String> overviewDistInfo;
    private javax.swing.JScrollPane overviewDistScroll;
    private java.awt.Label overviewDistTitle;
    private javax.swing.JList<String> overviewGradeInfo;
    private javax.swing.JList<String> overviewGradeNameInfo;
    private javax.swing.JScrollPane overviewGradeNameScroll;
    private java.awt.Label overviewGradeNameTitle;
    private javax.swing.JScrollPane overviewGradeScroll;
    private java.awt.Label overviewGradeTitle;
    private javax.swing.JPanel panEdit;
    private javax.swing.JPanel panHome;
    private javax.swing.JPanel panOverview;
    private javax.swing.JPanel panPredict;
    private javax.swing.JTabbedPane winTabs;
    // End of variables declaration//GEN-END:variables
}
