/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alpha;

/**
 *
 * @author Caleb
 */
public class semesterAddRem extends javax.swing.JFrame {
    private GUI mainframe;

    /**
     * Creates new form semesterAddRem
     * and gets a reference to the window that created this pop-up
     */
    public semesterAddRem(GUI mainframe) {
        initComponents();
        this.mainframe = mainframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAddSem = new javax.swing.JPanel();
        labelSemTerm = new java.awt.Label();
        addCBoxSemTerm = new javax.swing.JComboBox<>();
        labelSemYear = new java.awt.Label();
        addCBoxSemYear = new javax.swing.JComboBox<>();
        addButCancel = new javax.swing.JButton();
        addButCreateSem = new javax.swing.JButton();
        panelRemSem = new javax.swing.JPanel();
        remScrollPane = new javax.swing.JScrollPane();
        remList = new javax.swing.JList<>();
        remButCancel = new javax.swing.JButton();
        remButRemSem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("Add/Remove Semester");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                semesterAddRem.this.windowClosing(evt);
            }
        });

        labelSemTerm.setText("Semester Term");

        addCBoxSemTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spring", "Summer", "Fall", "Winter" }));

        labelSemYear.setText("Semester Year");

        addCBoxSemYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020" }));

        addButCancel.setText("Cancel");
        addButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButCancelActionPerformed(evt);
            }
        });

        addButCreateSem.setText("Create Semester");
        addButCreateSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButCreateSemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddSemLayout = new javax.swing.GroupLayout(panelAddSem);
        panelAddSem.setLayout(panelAddSemLayout);
        panelAddSemLayout.setHorizontalGroup(
            panelAddSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddSemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addButCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSemYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSemTerm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCBoxSemTerm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCBoxSemYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButCreateSem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAddSemLayout.setVerticalGroup(
            panelAddSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddSemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCBoxSemTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSemTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSemYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCBoxSemYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButCancel)
                    .addComponent(addButCreateSem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Semester", panelAddSem);

        remList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        remScrollPane.setViewportView(remList);

        remButCancel.setText("Cancel");
        remButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remButCancelActionPerformed(evt);
            }
        });

        remButRemSem.setText("Remove Semester");
        remButRemSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remButRemSemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRemSemLayout = new javax.swing.GroupLayout(panelRemSem);
        panelRemSem.setLayout(panelRemSemLayout);
        panelRemSemLayout.setHorizontalGroup(
            panelRemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemSemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remScrollPane)
                    .addGroup(panelRemSemLayout.createSequentialGroup()
                        .addComponent(remButCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remButRemSem, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRemSemLayout.setVerticalGroup(
            panelRemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemSemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remButCancel)
                    .addComponent(remButRemSem))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove Semester", panelRemSem);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("panelAddRemSem");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Action taken when file->exit is taken. Simply closes the entire system (The entire app)
    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fileExitActionPerformed

    // Action performed when the cancel button on the add Semester tab is clicked
    // Currently re-enables the original GUI
    // Then disposes the pop-up window
    private void addButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButCancelActionPerformed
        // TODO add your handling code here:
        mainframe.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_addButCancelActionPerformed

    // Action performed when window is closed
    // Currently re-enables the original GUI that instantiated this pop-up window
    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
        // TODO add your handling code here:
        mainframe.setEnabled(true);
    }//GEN-LAST:event_windowClosing

    //Action performed when cancel button on remove tab
    // Currently re-enables the original GUI that instantiated this pop-up window
    // Then disposes the pop-up window
    private void remButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remButCancelActionPerformed
        // TODO add your handling code here:
        mainframe.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_remButCancelActionPerformed

    private void addButCreateSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButCreateSemActionPerformed
        // TODO add your handling code here:
         mainframe.addSemester(new classHandler("Testing", ((String)addCBoxSemTerm.getSelectedItem()+(String)addCBoxSemYear.getSelectedItem())));
    }//GEN-LAST:event_addButCreateSemActionPerformed

    private void remButRemSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remButRemSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remButRemSemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButCancel;
    private javax.swing.JButton addButCreateSem;
    private javax.swing.JComboBox<String> addCBoxSemTerm;
    private javax.swing.JComboBox<String> addCBoxSemYear;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label labelSemTerm;
    private java.awt.Label labelSemYear;
    private javax.swing.JPanel panelAddSem;
    private javax.swing.JPanel panelRemSem;
    private javax.swing.JButton remButCancel;
    private javax.swing.JButton remButRemSem;
    private javax.swing.JList<String> remList;
    private javax.swing.JScrollPane remScrollPane;
    // End of variables declaration//GEN-END:variables
}
